package cn.douzy.remainder.dao;
import cn.douzy.base.framework.BaseMapper;
import cn.douzy.remainder.entity.ConType;

/**
 *com.wos.mapper.ConTypeMapper.java
 *2017-07-12 02:40:35
 * This was class generated by ant velocity
 */
public interface ConTypeMapper extends BaseMapper<ConType,java.lang.Integer> {
 
}


