package cn.douzy.remainder.dao;
import cn.douzy.base.framework.BaseMapper;
import cn.douzy.remainder.entity.Content;

/**
 *com.wos.mapper.ContentMapper.java
 *2017-07-12 02:40:35
 * This was class generated by ant velocity
 */
public interface ContentMapper extends BaseMapper<Content,java.lang.Integer> {
 
}


