package cn.douzy.remainder.dao;
import cn.douzy.base.framework.BaseMapper;
import cn.douzy.remainder.entity.Record;

/**
 *com.wos.mapper.RecordMapper.java
 *2017-07-12 02:40:35
 * This was class generated by ant velocity
 */
public interface RecordMapper extends BaseMapper<Record,java.lang.Integer> {
 
}


