package cn.douzy.remainder.entity;

import java.io.Serializable;
import java.util.Date;

public class Content implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.id
     *
     * @mbggenerated Wed Jul 12 14:40:34 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.create_time
     *
     * @mbggenerated Wed Jul 12 14:40:34 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.con
     *
     * @mbggenerated Wed Jul 12 14:40:34 CST 2017
     */
    private String con;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table content
     *
     * @mbggenerated Wed Jul 12 14:40:34 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.id
     *
     * @return the value of content.id
     *
     * @mbggenerated Wed Jul 12 14:40:34 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.id
     *
     * @param id the value for content.id
     *
     * @mbggenerated Wed Jul 12 14:40:34 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.create_time
     *
     * @return the value of content.create_time
     *
     * @mbggenerated Wed Jul 12 14:40:34 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.create_time
     *
     * @param createTime the value for content.create_time
     *
     * @mbggenerated Wed Jul 12 14:40:34 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.con
     *
     * @return the value of content.con
     *
     * @mbggenerated Wed Jul 12 14:40:34 CST 2017
     */
    public String getCon() {
        return con;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.con
     *
     * @param con the value for content.con
     *
     * @mbggenerated Wed Jul 12 14:40:34 CST 2017
     */
    public void setCon(String con) {
        this.con = con == null ? null : con.trim();
    }
}